name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  DOTNET_VERSION: '8.x'

on:
  workflow_dispatch:
    inputs:
      AZURE_WEBAPP_NAME:
        description: 'Azure Web App Name'
        required: true
        type: string
      ENVIRONMENT:
        description: 'Environment'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENVIRONMENT }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ${{ vars.APP_PATH }} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ vars.APP_PATH }} -c Release -o ${{ vars.APP_PATH }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ vars.APP_PATH }}/myapp

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event.inputs.ENVIRONMENT }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.event.inputs.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: .
